# Generated by Django 5.2.8 on 2025-11-25 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Sugerencia', 'Sugerencia'), ('Error', 'Reporte de Error'), ('Felicitacion', 'Felicitación'), ('Otro', 'Otro')], default='Sugerencia', max_length=20)),
                ('mensaje', models.TextField(verbose_name='Tu mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False, verbose_name='Leído por Admin')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia / Feedback',
                'verbose_name_plural': 'Buzón de Sugerencias',
                'ordering': ['-fecha'],
            },
        ),
    ]
