# Generated by Django 5.2.8 on 2025-11-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Habilidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('veces_solicitada', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre mí'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='carrera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='estado_cuenta',
            field=models.CharField(choices=[('Activo', 'Activo'), ('PendienteActivacion', 'Pendiente de Activación'), ('Bloqueado', 'Bloqueado')], default='PendienteActivacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Administrador', 'Administrador')], default='Estudiante', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='habilidades_buscadas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_buscan', to='accounts.habilidad', verbose_name='Habilidades que busco'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='habilidades_ofrecidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_ofrecen', to='accounts.habilidad', verbose_name='Habilidades que ofrezco'),
        ),
    ]
