# Generated by Django 5.2.8 on 2025-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_habilidad_customuser_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='bi-award', max_length=50)),
                ('requisito', models.CharField(help_text='Ej. Completar 5 intercambios', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='reputacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='insignias',
            field=models.ManyToManyField(blank=True, related_name='ganadores', to='accounts.insignia'),
        ),
    ]
