# Generated by Django 5.2.8 on 2025-11-24 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_habilidad_customuser_biografia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('EnProgreso', 'En Progreso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('habilidad_ofrecida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_como_ofrecida', to='accounts.habilidad')),
                ('habilidad_solicitada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_como_solicitada', to='accounts.habilidad')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
