# Generated by Django 5.2.8 on 2025-11-24 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0002_reporte_resena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='intercambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='intercambios.intercambio'),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('intercambio', 'autor')},
        ),
    ]
